/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#13131b",
        surface: "#13131b",
        "surface-dim": "#13131b",
        "surface-bright": "#393841",
        "surface-container-lowest": "#0d0d15",
        "surface-container-low": "#1b1b23",
        "surface-container": "#1f1f27",
        "surface-container-high": "#292932",
        "surface-container-highest": "#34343d",
        "surface-variant": "#34343d",
        "on-surface": "#e4e1ed",
        "on-surface-variant": "#c7c4d7",
        "on-background": "#e4e1ed",
        "inverse-surface": "#e4e1ed",
        "inverse-on-surface": "#303038",
        primary: "#c0c1ff",
        "on-primary": "#1000a9",
        "primary-container": "#8083ff",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary-fixed-dim": "#c0c1ff",
        "inverse-primary": "#494bd6",
        secondary: "#bdc2ff",
        "on-secondary": "#131e8c",
        "secondary-container": "#2f3aa3",
        "on-secondary-container": "#a8afff",
        "secondary-fixed": "#e0e0ff",
        "secondary-fixed-dim": "#bdc2ff",
        tertiary: "#ffb783",
        "on-tertiary": "#4f2500",
        "tertiary-container": "#d97721",
        "on-tertiary-container": "#452000",
        "tertiary-fixed": "#ffdcc5",
        "tertiary-fixed-dim": "#ffb783",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        outline: "#908fa0",
        "outline-variant": "#464554",
        "surface-tint": "#c0c1ff",
        border: "#1E2333",
      },
      fontFamily: {
        body: ["Inter", "sans-serif"],
        display: ["Inter", "sans-serif"],
        heading: ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "data-tabular": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        body: ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        display: ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        heading: ["22px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "data-tabular": ["14px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        base: "4px",
        xxs: "4px",
        xs: "8px",
        sm: "12px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        layout_margin: "24px",
        layout_gutter: "16px",
      },
      keyframes: {
        "subtle-pulse": {
          "0%": { boxShadow: "0 0 0 0 rgba(217, 119, 33, 0.4)" },
          "70%": { boxShadow: "0 0 0 6px rgba(217, 119, 33, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(217, 119, 33, 0)" },
        },
        "typing-dot": {
          "0%, 100%": { opacity: "0.3" },
          "50%": { opacity: "1" },
        },
      },
      animation: {
        "amber-pulse": "subtle-pulse 2s infinite",
        "typing-dot": "typing-dot 1.4s infinite ease-in-out",
      },
    },
  },
  plugins: [],
}
